### PR TITLE
added extra try catch around a connection string

### PR DESCRIPTION
**Pull request by crshnbrn66**
I was having trouble using the Open-Oracleconnection then I added an extra try catch: 

[Oracle.ManagedDataAccess.Client.OracleConnection]::new($sb)

        try{
        $sb["ConnectionString"] = $ConnectionString
        }
        catch
        {$sb = [Oracle.ManagedDataAccess.Client.OracleConnectionStringBuilder]::new($ConnectionString)}

I was then able to get the connection to the db to work.. 

In addition I had to reflect in your Custom VB Dll before calling your Module to be imported: 
[System.Reflection.Assembly]::LoadFile("C:\temp\SimplySql\1.3.2\DataReaderToPSObject.dll")

### CODE REVIEW

**Comment by crshnbrn66** [comment]
Also Great job on this Module SAVED me A TON of Time ... Nice job

**Comment by mithrandyr** [comment]
@crshnbrn66 Hey, did you make sure that the module "DataReaderToPSObject.dll" is not marked as "blocked"?  As far as I know. I've never needed to do an additional load besides what is located in "SimplySql.psm1" line 8...
`Add-Type -Path "$PSScriptRoot\DataReaderToPSObject.dll"`

What version of PowerShell are you using?
I'll also take a look at the OracleConnection piece.  Can you also confirm what version of the module you are using?  Thanks!

Glad you found the module helpful!

**Comment by mithrandyr** [comment]
I've release 1.3.3 to PowerShell Gallery that fixes the root issue with -ConnectionString on Open-OracleConnection.  As for the other issue, if you can help me figure out the cause, I'd love to fix that as well.

**Comment by crshnbrn66** [comment]
I checked your dll isn't blocked.  I did have to do this to get it to where I need to run: 
find-module simplySQL | save-module -path ((gi ($pwd.path)).fullname) 
Version 1.3.2 of your module is what I did the pull request from

**Comment by mithrandyr** [comment]
`Install-Module SimplySql -Scope CurrentUser`
that should work just fine - I've tested it on a few different computers and had no issues using the module after that.  I'm going to close this PullRequest because the first issue I have fixed in 1.3.3.  And the DLL loading is not reproducible.  Thanks for using the module and if you have any other issues or suggestions, please share them!

**Pull request closed without merging**
