### PR TITLE
Add -OutputAs, -TrustServerCertificate and ReturnProviderSpecificTypes.

### PR DESCRIPTION
**Pull request by ili101**
Hi
I just switched to this module from the Postgres ODBC one as I needed some more functionality.
There are 3 things I needed to get it working for me that are included in here.
(Sorry for the slightly messy Git change view, VSCode cleared some trailing spaces from the code)

1. Added Open-PostGreConnection **-TrustServerCertificate** as it needed if you have a DB certificate but it's not a valid one (as the **-RequireSSL** options are "Require" and "Prefer" and not "Disable").
2. Added Invoke-SqlQuery **-OutputAs**  with options 'DataSet', 'DataTables', 'DataRows'. this is similar to https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps (If not set keep your existing code for backward compatibility)
3. **ReturnProviderSpecificTypes** added to the PostGreProvider Class, this gives the option to use the Provider-specific types from https://www.npgsql.org/doc/types/basic.html. However I don't know how you prefer to add the switch to activate it as Invoke-SqlQuery is shared with all DB types and this is Postgres specific option. So a switch needs to be added somewhere and the line `if ($true) #Replace with a switch` need to be modified.

Thank you

### CODE REVIEW

**Comment by ili101** [comment]
Correction regarding ReturnProviderSpecificTypes, It looks like this option is not Postgres specific but used in other connection as well, for example:
MySQL https://dev.mysql.com/doc/dev/connector-net/8.0/html/T_MySql_Data_MySqlClient_MySqlDataAdapter.htm
Oracle https://docs.oracle.com/cd/B28359_01/win.111/b28375/featTypes.htm https://docs.oracle.com/database/121/ODPNT/featUDTs.htm#ODPNT402
So it might be good to add a switch globally to Invoke-SqlQuery. (I only tested it myself on Postgres)

**Comment by mithrandyr** [comment]
@ili101 I've done a brief review of your changes... In principal, I like the ideas behind them -- but I'm not sure I can accept them as is.
- Provider Specific Types... this should probably be a setting on the connection that can be overridden on invoke-sqlquery/sqlscalar.  However, I'm not entirely sure how this will play with the -Stream option (which generates PSObjects)
- Invoke-SqlQuery returnAs -- I feel like this option violates the spirit of PowerShell, but I might be wrong... I'm thinking of instead add a switch option that will return the dataset object -- otherwise it will use the existing behavior.  I'll also look into improving the help on the command regarding these behaviors.
- PostGre trust option -- that looks good.

**Comment by ili101** [comment]
@mithrandyr regarding your comment.
* regarding -OutputAs, what do you mean by "I feel like this option violates the spirit of PowerShell"?
I like this option for a few reasons:
First, you know exactly what output type to expect so you don't get surprised if suddenly you get a DataTables instead of DataRows for example like in the original code.
Second, In 99% of the cases, I prefer getting a DataTable. An array of DataRows just feels wrong, most of the DataRows objects functionality is controlled by its parent DataTable so I don't understand way striping the DataTable and replacing it with an array is something I will ever want. And I usually don't need the DataSet if I have one DataTable.
So -DataSet switch will be technically usable but less convenient to use for me.

* regarding the Provider Specific Types, I don't know VB but I looked at your code at https://github.com/mithrandyr/DataReaderToPSObject/blob/master/DataReaderToPSObject.vb
I don't understand what is the purpose of the `Case "<Type>"` part. If you remove all the Cases and leave only the code in the "Else" with the `dataReader.GetValue` method to handle all types wouldn't it be exactly the same? As the GetValue uses the [Read mappings](https://www.npgsql.org/doc/types/basic.html) and will map it correctly anyway?
To get the Provider Specific Types functionality in the Stream mode you need to replace the `dataReader.GetValue` and/or `dataReader.Get<Type>` with `dataReader.GetProviderSpecificValue`

**Comment by mithrandyr** [comment]
@ili101  -- DataReader.GetValue has to do implicit type conversions which are slow --- hence doing parsing and pulling the proper type immediately out.  Currently -Stream has a roughly 2x performance penalty, this would increase more if I only used DataReader.GetValue -- at least this was my recollection when I di this work years ago.  If you can make performance improvements to the DataReaderToPSObject, I would be grateful.

Ok.. for your 1st point, returning a DataSet probably won't be worth it -- so i'll do a -AsDataTable (or something similar) switch that will return datatables.  otherwise it will use the existing logic.

**Comment by ili101** [comment]
As `-AsDataTable` added in https://github.com/mithrandyr/SimplySql/commit/f7c954b5423985754e628c20129ace38fb79c005 ( #13 adding the -AsDataTable switch.)
And `-TrustSSL` added in https://github.com/mithrandyr/SimplySql/commit/86fb2ec20c90676803085820a9a4137689bf2030 (fixed #6 by adding [ValidateNotNullOrEmpty()] to -ConnectionName parameters)
I removed the changes from my fork and updated it.
I added the switch `Invoke-SqlQuery -ProviderTypes` and it now supports `-Stream`. however the Stream support is implemented in PowerShell and not in the dll so it's 3 times slower when using the 2 switches together.

**Comment by mithrandyr** [comment]
@ili101 Thanks for this work -- can you also contribute some pester tests to verify that the switch works properly?

Also, I'm not sure I want to bring additional slowness into the module (-ProviderTypes & -Stream) -- So help me understand the use case of combining -ProviderTypes w/ -Stream?  From my perspective, the -Stream was for being able to interact with the output in a more explicit powershell way (IE think of sysadmin versus developer), would this use case really care for provider specific values?  That seems to be a developer centric request, which would be satisfied with getting datatable/datarow objects back.

**Comment by ili101** [comment]
Hi
I added test for Postgre as documented here https://www.npgsql.org/doc/types/basic.html .
I don't have Oracle installed but you can preform similar tests as documented here https://docs.oracle.com/cd/B28359_01/win.111/b28375/featTypes.htm and here https://docs.oracle.com/database/121/ODPNT/featUDTs.htm#ODPNT379 .
I didn't find the documentation for MySQL an SQLite so I don't know what spacial types they have to test.

Regarding the -ProviderTypes & -Stream combo, in my case I needed to export some data to csv with dates and times in the correct format from the DB, the csv module I used did not support DataTable so -Steam could have been useful to me.
I removed the slow ProviderTypes + Stream PowerShell implementation I added earlier and added it to the dll so it's fast now.
dll changes: https://github.com/mithrandyr/DataReaderToPSObject/pull/1

**Comment by mithrandyr** [comment]
@ili101 Thank you for this work -- I'm reviewing and hope to be able to merge the changes in the next couple of weeks!

**Comment by mithrandyr** [comment]
@ili101 I've pulled your work into a separate branch for testing (and used that to update the version history, etc) -- version 1.6.0 has your work and will be published to powershell gallery in the next couple of hours.  Thanks for your help!

**Pull request closed without merging**
