### PR TITLE
Updated Mysql.data.dll version and related dependencies

### PR DESCRIPTION
**Pull request by twerthi**
Updated mysql.data.dll version and related dependencies to include the clear_text plubin.

### CODE REVIEW

**Comment by twerthi** [comment]
@mithrandyr, does this pass muster?

**Comment by twerthi** [comment]
This will resolve #57 and #60

**Review by mithrandyr — APPROVED** [review]

**Comment by mithrandyr** [comment]
@twerthi  -- can you update (or create New PR) and target the v1.9 branch that I created.  thanks!

**Comment by twerthi** [comment]
@mithrandyr Done!

**Pull request merged**
