### PR TITLE
Add mysql advanced options

### PR DESCRIPTION
**Pull request by tocano33**
Added a hashtable parameter to the 'default' ParameterSet for those that don't make an actual string ConnectionString, to make it easier for them to specify various connection options

### CODE REVIEW

**Comment by mithrandyr** [comment]
@tocano33 I like the idea -- however, I would like to make this standard across all the providers currently in SimplySql -- would you be willing to extend this work to the SQLite, MSSQL, PostGres and Oracle providers?

**Comment by tocano33** [comment]
I'm willing to look into it but dont know if those providers handle
additional options in the same way.

**Comment by mithrandyr** [comment]
@tocano33 
PostGres (NPGSQL) --> https://www.npgsql.org/doc/api/Npgsql.NpgsqlConnectionStringBuilder.html
Oracle --> https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odpnt/featConnecting.html#GUID-BCF2F215-C25F-403C-8D18-B03A69BC7104
SQLite --> https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki
MSSQL --> https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=netframework-4.7.2

You should be able to use the same pattern in the other provider files that you have in the MySQL one...

**Comment by mithrandyr** [comment]
Superseded by version 2.0

**Pull request closed without merging**
