### PR TITLE
Add Linux/MacOS Support for SQLite.

### PR DESCRIPTION
**Pull request by the-mentor**
I've added Linux and MacOS support for the SQLite component of the module.
I've tested it on WSL and Native Linux and it works as expected.

Let me know if you have any questions.

-DM

### CODE REVIEW

**Comment by mithrandyr** [comment]
Is there not a nuget package for SQLite that supports .NET Standard 2.0?  If so, then I should be able to simply incorporate that package and not have to do the additional checks.  There is another repository that I use for tracking the nuget packages for the different providers.

**Comment by the-mentor** [comment]
This PR is baes on a nuget package its just that every OS has its own native packages.
It's bass on this 
https://www.nuget.org/packages/System.Data.SQLite.Core/

-DM

**Comment by oitptobbe** [comment]
@the-mentor Missing System.Data.SQLite.dll for osx.

**Comment by mithrandyr** [comment]
@the-mentor  - apologies for the delay.   I'm finally getting around to making the module truly standard and able to be run across Windows PowerShell and PS7. It is required a significant rewrite (under the covers) of the module, but the result should be a stable codebase that runs on both platforms (.NET Framework and .NET) and will enable keeping the underlying providers up to date more easily. I'm tagging this PR and will close it (without accepting it) once the new release (2.0.0) is completed.

**Comment by mithrandyr** [comment]
Superseded by version 2.0

**Pull request closed without merging**
